export enum ENodeEvent {
  MOUNTED = "MOUNTED",
  UNMOUNTED = "UNMOUNTED",
  BEFORE_REPLACE = "BEFORE_REPLACE",
  AFTER_REPLACE = "AFTER_REPLACE",
  RECEIVE_PARENT = "RECEIVE_PARENT",
  REPLACED = "REPLACED",
  UPDATED = "UPDATED",
  LOADED = "LOADED"
}
