export enum ENodeEvent {
  MOUNTED = "MOUNTED",
  UNMOUNTED = "UNMOUNTED",
  BEFORE_UNMOUNT = "BEFORE_UNMOUNT",
  BEFORE_REPLACE = "BEFORE_REPLACE",
  BEFORE_RENDER = "BEFORE_RENDER",
  AFTER_REPLACE = "AFTER_REPLACE",
  RECEIVE_PARENT = "RECEIVE_PARENT",
  CLEANUP = "CLEANUP",
  REPLACED = "REPLACED",
  UPDATED = "UPDATED",
  LOADED = "LOADED",
}
